# docker-compose.prod.yml

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: simagaev/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
  
  frontend:
    image: simagaev/taski_frontend
    env_file: .env
    volumes:
      - static:/staticfiles
  
  gateway:
    image: simagaev/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - "80:80"